model:
  name: deit_tiny
  num_classes: 200
  pretrained: true
  drop_path_rate: 0.0
  drop_rate: 0.0
  attn_drop_rate: 0.0

data:
  dataset: tiny_imagenet
  root: dataset/tiny-imagenet-200
  img_size: 224
  batch_size: 256
  num_workers: 4
  train_crop_scale_min: 0.8
  train_crop_scale_max: 1.0
  train_crop_ratio_min: 0.75
  train_crop_ratio_max: 1.3333333333333333

train:
  seed: 42
  deterministic: true
  epochs: 50
  lr: 5.0e-4
  weight_decay: 0.05
  label_smoothing: 0.0
  warmup_epochs: 5
  min_lr: 1.0e-6
  max_grad_norm: 1.0
  amp: true
  device: cuda
